version: 0.2

env:

phases:
  install:
    runtime-versions:
      node: 14
  pre_build:
    - echo Running npm install
    - npm install
  build:
    - echo Running Hardhat testing
    - npx hardhat test
