version: 0.2

phases:
  install:
    runtime-versions:
      node: 14
  pre_build:
    commands:
      - echo Running npm install
      - npm install
  build:
    commands:
      - echo Running Hardhat testing
      - npx hardhat test
